package com.restapi.wmsservice.enums;

public enum NotificationType {
    WORKSHOP_REQUEST_SUBMITTED,
    WORKSHOP_REQUEST_APPROVED,
    WORKSHOP_REQUEST_CANCELLED,
    PLANNING_CREATED,
    PLANNING_APPROVED,
    PLANNING_EXECUTION_STARTED,
    PLANNING_COMPLETED,
    PLANNING_FAILED,
    PURCHASE_APPROVED,
    PURCHASE_ORDERED,
    PURCHASE_RECEIVED,
    PURCHASE_CANCELLED,
    RECYCLE_STARTED,
    RECYCLE_COMPLETED,
    RECYCLE_FAILED,
    ASSEMBLY_STARTED,
    ASSEMBLY_COMPLETED,
    ASSEMBLY_FAILED,
    TRANSFER_IN_TRANSIT,
    TRANSFER_COMPLETED,
    TRANSFER_CANCELLED
}
